"""
ExplorationPlanner — LangGraph sub-graph (Sprint 5 / Task 3).

Input:  start_url, sfg_store, existing_skills
Output: list[TestHypothesis]

Graph:
  START → crawl → cluster → gap_analysis → hypothesis → judge → END
  judge routes back to hypothesis on approved=False (max 2 retries)
"""
from __future__ import annotations

from typing import TypedDict

import numpy as np
from loguru import logger
from langgraph.graph import StateGraph, START, END
from pydantic import BaseModel, ConfigDict, Field

from src.config_loader import get_exploration_config
from src.contractskill.compiler import ContractSkill
from src.contractskill.crawler import SFGCrawler, CrawlerConfig
from src.contractskill.sfg import SFGNode, SFGStore
from src.explorer.hypothesis import TestHypothesis
from src.llm.adapter import DEFAULT_MODEL, OllamaAdapter, _inference_semaphore
from src.llm.instructor_client import InstructorClient, StructuredGenerationError
from src.llm.judge_client import JudgeClient
from src.perception.grounder import Grounder

# ──────────────────────────────────────────────────────────────────────────────
# Constants
# ──────────────────────────────────────────────────────────────────────────────

_MAX_RETRIES = 2
_COSINE_THRESHOLD = 0.7
_MAX_UNCOVERED_FLOWS = 5
_KEYWORD_OVERLAP_MIN = 2
# Minimum fraction of the shorter goal's meaningful words that must be shared
# for a hypothesis to be attributed to an existing ContractSkill. Earned, not
# seeded — drives Sprint 5 `skills_reused`.
_SKILL_MATCH_RATIO = 0.3
_HYPOTHESIS_GENERATION_MODEL = DEFAULT_MODEL

_STOPWORDS = frozenset({"the", "a", "an", "is", "are", "in", "on", "to", "of", "and", "or", "for"})


# ──────────────────────────────────────────────────────────────────────────────
# Internal Pydantic schemas (not exported)
# ──────────────────────────────────────────────────────────────────────────────


class _TestHypothesisItem(BaseModel):
    """Single hypothesis as generated by the LLM."""

    model_config = ConfigDict(extra="forbid")

    goal: str
    preconditions: list[str] = Field(default_factory=list)
    steps: list[str] = Field(default_factory=list)
    expected_outcome: str
    confidence: float = Field(default=0.5, ge=0.0, le=1.0)


class _TestHypothesisList(BaseModel):
    """LLM response schema for hypothesis generation."""

    model_config = ConfigDict(extra="forbid")

    hypotheses: list[_TestHypothesisItem] = Field(default_factory=list)


# ──────────────────────────────────────────────────────────────────────────────
# LangGraph state
# ──────────────────────────────────────────────────────────────────────────────


class PlannerState(TypedDict):
    start_url: str
    sfg_store: SFGStore
    existing_skills: list[ContractSkill]
    sfg_nodes: list[SFGNode]           # filled by crawl_node
    clusters: list[list[SFGNode]]      # filled by cluster_node
    uncovered_flows: list[str]         # filled by gap_analysis_node
    hypotheses: list[TestHypothesis]   # filled by hypothesis_node
    hypothesis_revision_count: int     # for retry loop limit
    judge_approved: bool               # filled by judge_node


# ──────────────────────────────────────────────────────────────────────────────
# Helpers
# ──────────────────────────────────────────────────────────────────────────────


def _cosine_similarity(a: list[float], b: list[float]) -> float:
    """Return cosine similarity between two vectors. Returns 0.0 on error."""
    va = np.array(a, dtype=np.float32)
    vb = np.array(b, dtype=np.float32)
    norm_a = float(np.linalg.norm(va))
    norm_b = float(np.linalg.norm(vb))
    if norm_a == 0.0 or norm_b == 0.0:
        return 0.0
    return float(np.dot(va, vb) / (norm_a * norm_b))


def _meaningful_words(text: str) -> set[str]:
    """Lowercased content words: drop stopwords and tokens of length <= 2."""
    return {w.lower() for w in text.split() if w.lower() not in _STOPWORDS and len(w) > 2}


def _keyword_overlap(text_a: str, text_b: str) -> int:
    """Return the count of common content words between two strings."""
    return len(_meaningful_words(text_a) & _meaningful_words(text_b))


def _words_relate(a: str, b: str) -> bool:
    """True if two content words are the same concept: equal, or one is a prefix
    of the other with the shorter word >= 4 chars (e.g. mark/marking,
    complete/completed). The 4-char floor avoids spurious short-prefix hits
    (car/care). Captures genuine morphological variants, not fuzzy guesses."""
    if a == b:
        return True
    shorter, longer = (a, b) if len(a) <= len(b) else (b, a)
    return len(shorter) >= 4 and longer.startswith(shorter)


def _match_skill(goal: str, skills: list[ContractSkill]) -> str | None:
    """Attribute a hypothesis *goal* to an existing ContractSkill by genuine
    keyword overlap of goal statements.

    Returns the skill_id of the BEST-overlapping skill (highest shared fraction
    of the shorter goal's meaningful words), provided it clears
    ``_SKILL_MATCH_RATIO``; else None. Best-match (not first-match) so distinct
    hypotheses attribute to their most-relevant skill, giving genuine skill
    diversity. Pure keyword overlap — no LLM call (preserves the inference
    Semaphore budget) and no artificial seeding: the match must be earned.
    """
    if not skills:
        return None
    goal_words = _meaningful_words(goal)
    if not goal_words:
        return None
    best_id: str | None = None
    best_ratio = 0.0
    for skill in skills:
        skill_words = _meaningful_words(skill.goal)
        if not skill_words:
            continue
        # Count goal words that relate (equal or morphological prefix) to any
        # skill word — so "marking"/"completed" attribute to "mark"/"complete".
        overlap = sum(
            1 for gw in goal_words if any(_words_relate(gw, sw) for sw in skill_words)
        )
        if overlap == 0:
            continue
        ratio = overlap / min(len(goal_words), len(skill_words))
        if ratio > best_ratio:
            best_ratio = ratio
            best_id = skill.skill_id
    return best_id if best_ratio >= _SKILL_MATCH_RATIO else None


def _hypotheses_to_text(hypotheses: list[TestHypothesis]) -> str:
    """Serialize hypotheses to a text block for judge evaluation."""
    lines = []
    for i, h in enumerate(hypotheses, 1):
        lines.append(f"Hypothesis {i}: {h.goal}")
        lines.append(f"  Steps: {'; '.join(h.steps)}")
        lines.append(f"  Expected: {h.expected_outcome}")
    return "\n".join(lines) if lines else "(none)"


# ──────────────────────────────────────────────────────────────────────────────
# Node implementations
# ──────────────────────────────────────────────────────────────────────────────


async def _crawl_node(state: PlannerState) -> dict:
    """Node 1: Run SFGCrawler to discover application state flow graph nodes."""
    start_url: str = state["start_url"]
    sfg_store: SFGStore = state["sfg_store"]

    try:
        exploration_cfg = get_exploration_config()
        crawler_config = CrawlerConfig(
            max_time_minutes=int(exploration_cfg.get("max_time_minutes", 10)),
            max_tokens=int(exploration_cfg.get("max_tokens", 50_000)),
            max_pages=int(exploration_cfg.get("max_pages", 20)),
            max_depth=int(exploration_cfg.get("max_depth", 4)),
            max_outgoing_per_node=int(exploration_cfg.get("max_outgoing_per_node", 10)),
        )

        grounder = Grounder()
        crawler = SFGCrawler(sfg_store, grounder, crawler_config)

        logger.info(f"ExplorationPlanner.crawl_node: crawling {start_url!r}")
        await crawler.crawl(start_url)

        # Retrieve all discovered nodes from the store
        nodes = sfg_store.get_nodes_by_url_prefix(start_url)
        logger.info(f"ExplorationPlanner.crawl_node: discovered {len(nodes)} nodes")
        return {"sfg_nodes": nodes}

    except Exception as exc:
        logger.warning(f"ExplorationPlanner.crawl_node: crawler failed — {exc!r}")
        return {"sfg_nodes": []}


async def _cluster_node(state: PlannerState) -> dict:
    """Node 2: Cluster SFG nodes by pam_content cosine similarity (greedy)."""
    nodes: list[SFGNode] = state["sfg_nodes"]

    if not nodes:
        return {"clusters": []}

    adapter = OllamaAdapter()

    # Build (node, embedding) pairs — skip nodes that fail to embed
    embedded: list[tuple[SFGNode, list[float]]] = []
    for node in nodes:
        text = node.pam_content.strip()
        if not text:
            logger.debug(f"ExplorationPlanner.cluster_node: skipping empty pam_content for {node.node_id[:12]}")
            continue
        try:
            # OllamaAdapter.embed() does NOT hold _inference_semaphore internally
            # (unlike InstructorClient.create_structured/JudgeClient), so we acquire it here.
            async with _inference_semaphore:
                vec = await adapter.embed(text)
            embedded.append((node, vec))
        except Exception as exc:
            logger.warning(f"ExplorationPlanner.cluster_node: embed failed for {node.node_id[:12]} — {exc!r}")
            # skip this node

    await adapter.close()

    if not embedded:
        return {"clusters": []}

    # Greedy clustering: each cluster is represented by the mean of its embeddings
    cluster_nodes: list[list[SFGNode]] = []
    cluster_centroids: list[list[float]] = []

    for node, vec in embedded:
        placed = False
        for idx, centroid in enumerate(cluster_centroids):
            sim = _cosine_similarity(vec, centroid)
            if sim > _COSINE_THRESHOLD:
                cluster_nodes[idx].append(node)
                # Update centroid as running mean
                n = len(cluster_nodes[idx])
                updated = [
                    (centroid[j] * (n - 1) + vec[j]) / n
                    for j in range(len(centroid))
                ]
                cluster_centroids[idx] = updated
                placed = True
                break
        if not placed:
            cluster_nodes.append([node])
            cluster_centroids.append(vec)

    logger.info(f"ExplorationPlanner.cluster_node: {len(embedded)} nodes → {len(cluster_nodes)} clusters")
    return {"clusters": cluster_nodes}


async def _gap_analysis_node(state: PlannerState) -> dict:
    """Node 3: Compare clusters vs existing ContractSkills → find uncovered flows."""
    clusters: list[list[SFGNode]] = state["clusters"]
    existing_skills: list[ContractSkill] = state["existing_skills"]

    if not clusters:
        return {"uncovered_flows": []}

    # Build a combined text for each cluster from sample pam_content
    skill_goals: list[str] = [skill.goal for skill in existing_skills]

    uncovered: list[str] = []
    for cluster in clusters:
        if len(uncovered) >= _MAX_UNCOVERED_FLOWS:
            break

        # Sample representative content from this cluster (up to 3 nodes)
        sample_nodes = cluster[:3]
        cluster_text = " ".join(
            n.pam_content[:300] for n in sample_nodes if n.pam_content
        )
        if not cluster_text.strip():
            continue

        # Check if any existing skill covers this cluster
        covered = False
        for goal in skill_goals:
            if _keyword_overlap(cluster_text, goal) >= _KEYWORD_OVERLAP_MIN:
                covered = True
                break

        if not covered:
            # Describe the uncovered flow from available signals
            titles = [n.page_title for n in cluster if n.page_title]
            tags = list({tag for n in cluster for tag in n.coverage_tags})
            flow_desc = f"Uncovered flow: pages=[{', '.join(titles[:3])}] tags=[{', '.join(tags)}] content_snippet={cluster_text[:120]!r}"
            uncovered.append(flow_desc)

    logger.info(f"ExplorationPlanner.gap_analysis_node: {len(uncovered)} uncovered flows found")
    return {"uncovered_flows": uncovered}


async def _hypothesis_node(state: PlannerState) -> dict:
    """Node 4: Generate TestHypothesis list from uncovered flows via LLM."""
    uncovered_flows: list[str] = state["uncovered_flows"]
    start_url: str = state["start_url"]
    existing_skills: list[ContractSkill] = state["existing_skills"]
    existing_hypotheses: list[TestHypothesis] = state.get("hypotheses", [])
    revision_count: int = state.get("hypothesis_revision_count", 0)

    if not uncovered_flows:
        return {
            "hypotheses": existing_hypotheses,
            "hypothesis_revision_count": revision_count,
        }

    client = InstructorClient(model=_HYPOTHESIS_GENERATION_MODEL)
    all_hypotheses: list[TestHypothesis] = list(existing_hypotheses)

    for flow_desc in uncovered_flows:
        prompt = (
            f"You are a QA engineer generating test hypotheses for a web application.\n\n"
            f"Application URL: {start_url}\n"
            f"Uncovered flow description:\n{flow_desc}\n\n"
            f"Generate a list of 1-3 concrete test hypotheses for this flow. "
            f"Each hypothesis should have:\n"
            f"- goal: concise statement of what is being tested\n"
            f"- preconditions: list of conditions that must be true before the test\n"
            f"- steps: ordered list of user actions\n"
            f"- expected_outcome: what should happen if the feature works correctly\n"
            f"- confidence: 0.0-1.0 how confident you are this is a real gap\n\n"
            f"Return a JSON object with a 'hypotheses' array."
        )

        try:
            # _inference_semaphore is acquired internally by InstructorClient.create_structured()
            # (see src/llm/instructor_client.py line ~144).  Do NOT add an outer
            # `async with _inference_semaphore:` here — asyncio.Semaphore is non-reentrant
            # and wrapping again would deadlock.
            result: _TestHypothesisList = await client.create_structured(
                prompt=prompt,
                response_model=_TestHypothesisList,
                temperature=0.1,
            )
            for item in result.hypotheses:
                # Attribute this hypothesis to the most-relevant existing skill
                # (None if no genuine overlap) — drives Sprint 5 skills_reused.
                source_skill_id = _match_skill(item.goal, existing_skills)
                hypothesis = TestHypothesis(
                    hypothesis_id=None,  # type: ignore[arg-type]  # auto-generated
                    goal=item.goal,
                    start_url=start_url,
                    preconditions=item.preconditions,
                    steps=item.steps,
                    expected_outcome=item.expected_outcome,
                    source_skill_id=source_skill_id,
                    confidence=item.confidence,
                )
                all_hypotheses.append(hypothesis)

        except StructuredGenerationError as exc:
            logger.warning(f"ExplorationPlanner.hypothesis_node: LLM failed for flow — {exc!r}")
            # Continue with whatever hypotheses we have so far
        except Exception as exc:
            logger.warning(f"ExplorationPlanner.hypothesis_node: unexpected error — {exc!r}")

    await client.close()

    logger.info(f"ExplorationPlanner.hypothesis_node: generated {len(all_hypotheses)} total hypotheses")
    return {
        "hypotheses": all_hypotheses,
        "hypothesis_revision_count": revision_count,
    }


async def _judge_node(state: PlannerState) -> dict:
    """Node 5: 4-check judge to approve or request revision of hypotheses."""
    hypotheses: list[TestHypothesis] = state["hypotheses"]
    start_url: str = state["start_url"]
    revision_count: int = state.get("hypothesis_revision_count", 0)

    if not hypotheses:
        # Nothing to judge — approve empty set to terminate
        return {
            "judge_approved": True,
            "hypothesis_revision_count": revision_count,
        }

    instructor = InstructorClient()
    judge = JudgeClient(instructor)

    # Represent all hypotheses as a structured text for evaluation
    hypotheses_text = _hypotheses_to_text(hypotheses)
    requirement = (
        f"Test hypotheses for {start_url} — each hypothesis must:\n"
        f"1. State a testable goal for a real user flow\n"
        f"2. Have at least one precondition\n"
        f"3. Have at least one step\n"
        f"4. Have a concrete expected outcome"
    )

    # _inference_semaphore is acquired internally by InstructorClient.create_structured(),
    # which JudgeClient.evaluate() delegates to (see src/llm/judge_client.py and
    # src/llm/instructor_client.py).  Do NOT add an outer `async with _inference_semaphore:`
    # here — asyncio.Semaphore is non-reentrant and wrapping again would deadlock.
    verdict = await judge.evaluate(
        generated_code=hypotheses_text,
        requirement=requirement,
        domain="web_exploration",
    )

    await instructor.close()

    logger.info(
        f"ExplorationPlanner.judge_node: approved={verdict.approved} "
        f"confidence={verdict.confidence:.2f} "
        f"revision_count={revision_count}"
    )

    return {
        "judge_approved": verdict.approved,
        "hypothesis_revision_count": revision_count if verdict.approved else revision_count + 1,
    }


# ──────────────────────────────────────────────────────────────────────────────
# Routing logic
# ──────────────────────────────────────────────────────────────────────────────


def _route_after_judge(state: PlannerState) -> str:
    """Route to hypothesis (retry) or END based on judge verdict and retry count."""
    approved: bool = state.get("judge_approved", True)
    revision_count: int = state.get("hypothesis_revision_count", 0)

    if approved or revision_count >= _MAX_RETRIES:
        return END
    return "hypothesis"


# ──────────────────────────────────────────────────────────────────────────────
# Graph builder
# ──────────────────────────────────────────────────────────────────────────────


def _build_graph() -> object:
    """Build and compile the ExplorationPlanner LangGraph sub-graph."""
    graph = StateGraph(PlannerState)

    graph.add_node("crawl", _crawl_node)
    graph.add_node("cluster", _cluster_node)
    graph.add_node("gap_analysis", _gap_analysis_node)
    graph.add_node("hypothesis", _hypothesis_node)
    graph.add_node("judge", _judge_node)

    graph.add_edge(START, "crawl")
    graph.add_edge("crawl", "cluster")
    graph.add_edge("cluster", "gap_analysis")
    graph.add_edge("gap_analysis", "hypothesis")
    graph.add_edge("hypothesis", "judge")

    # Judge can route back to hypothesis (retry) or to END
    graph.add_conditional_edges(
        "judge",
        _route_after_judge,
        {"hypothesis": "hypothesis", END: END},
    )

    return graph.compile()


# ──────────────────────────────────────────────────────────────────────────────
# ExplorationPlanner
# ──────────────────────────────────────────────────────────────────────────────


class ExplorationPlanner:
    """LangGraph-based planner that discovers uncovered flows and generates TestHypotheses."""

    def __init__(self) -> None:
        self._graph = _build_graph()

    async def plan(
        self,
        start_url: str,
        sfg_store: SFGStore,
        existing_skills: list[ContractSkill],
    ) -> list[TestHypothesis]:
        """
        Run the exploration planning graph.

        Returns list[TestHypothesis] — empty list on failure, never raises.
        """
        initial_state: PlannerState = {
            "start_url": start_url,
            "sfg_store": sfg_store,
            "existing_skills": existing_skills,
            "sfg_nodes": [],
            "clusters": [],
            "uncovered_flows": [],
            "hypotheses": [],
            "hypothesis_revision_count": 0,
            "judge_approved": False,
        }

        try:
            logger.info(f"ExplorationPlanner.plan: starting for {start_url!r}")
            final_state = await self._graph.ainvoke(initial_state)
            hypotheses: list[TestHypothesis] = final_state.get("hypotheses", [])
            logger.info(f"ExplorationPlanner.plan: completed — {len(hypotheses)} hypotheses")
            return hypotheses

        except Exception as exc:
            logger.error(f"ExplorationPlanner.plan: unhandled error — {exc!r}")
            return []


__all__ = ["ExplorationPlanner", "PlannerState"]
