"""CI conftest — JUnit XML telemetry + observability hooks.

Loaded only inside the untrusted CI workflow (``pytest -p ci.conftest_ci`` or by
copying this file as ``conftest.py`` next to the e2e suite). It does NOT read
production credentials and never logs raw env values.

Telemetry channels (all surfaced via JUnit ``<properties>``):
    * ``attachment1`` — base64 PNG screenshot on failure
    * ``e2e_execution_latency_sec`` — wall-clock for each test
    * ``ai_semantic_consistency_score`` — when the item carries ``ai_score``
    * ``execution_count`` — for flaky-test detection
    * ``failure_trace`` — short failure message
"""
from __future__ import annotations

import asyncio
import base64
import json
import time
from collections.abc import AsyncIterator
from pathlib import Path
from typing import Any, Final

import pytest

REPORTS_DIR: Final[Path] = Path("workspace/untrusted_reports")
SESSION_SUMMARY_PATH: Final[Path] = REPORTS_DIR / "session_summary.json"

_TEST_MARKERS: Final[tuple[tuple[str, str], ...]] = (
    ("e2e", "End-to-end browser-driven test."),
    ("smoke", "Critical-path smoke test."),
    ("regression", "Regression test guarding against a known historical defect."),
    ("ai_generated", "Test whose body was generated by the QA agent."),
)


def pytest_configure(config: pytest.Config) -> None:
    """Register the four supported markers so unknown-marker warnings don't fire."""
    for name, description in _TEST_MARKERS:
        config.addinivalue_line("markers", f"{name}: {description}")
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)


# ─── Async page fixture ──────────────────────────────────────────────────────


@pytest.fixture
async def async_page(request: pytest.FixtureRequest) -> AsyncIterator[Any]:
    """Provide a Playwright async ``Page`` with trace=retain-on-failure baked in.

    Yields:
        A Playwright async page. On exit, the trace is saved when the test
        failed; otherwise the trace is discarded.
    """
    # Defer the playwright import: it's installed only inside the CI workflow,
    # not in the dev shell, so we don't want this module to fail to import.
    from playwright.async_api import async_playwright  # type: ignore[import-not-found]

    trace_path = REPORTS_DIR / "traces" / f"{request.node.nodeid.replace('/', '_')}.zip"
    trace_path.parent.mkdir(parents=True, exist_ok=True)

    async with async_playwright() as pw:
        browser = await pw.chromium.launch(headless=True)
        context = await browser.new_context()
        await context.tracing.start(screenshots=True, snapshots=True, sources=True)
        page = await context.new_page()

        request.node._async_page = page  # exposed for makereport screenshot capture

        try:
            yield page
        finally:
            failed = bool(getattr(request.node, "_e2e_failed", False))
            try:
                if failed:
                    await context.tracing.stop(path=str(trace_path))
                    request.node.user_properties.append(
                        ("attachment1", trace_path.as_posix())
                    )
                else:
                    await context.tracing.stop()
            finally:
                await context.close()
                await browser.close()


# ─── Per-test telemetry hook ─────────────────────────────────────────────────


@pytest.hookimpl(tryfirst=True, hookwrapper=True)
def pytest_runtest_makereport(
    item: pytest.Item, call: pytest.CallInfo[None]
) -> Any:
    """Record screenshot / latency / AI score / retry-count as JUnit properties."""
    outcome = yield
    report: pytest.TestReport = outcome.get_result()

    if report.when != "call":
        return

    elapsed = float(getattr(report, "duration", 0.0) or 0.0)
    item.user_properties.append(("e2e_execution_latency_sec", f"{elapsed:.6f}"))

    ai_score = getattr(item, "ai_score", None)
    if ai_score is not None:
        try:
            item.user_properties.append(
                ("ai_semantic_consistency_score", f"{float(ai_score):.6f}")
            )
        except (TypeError, ValueError):
            pass

    retry_count = int(getattr(item, "_retry_count", 0))
    item.user_properties.append(("execution_count", str(retry_count + 1)))

    if report.failed:
        item._e2e_failed = True  # type: ignore[attr-defined]

        if report.longreprtext:
            preview = report.longreprtext.splitlines()[-1][:240]
            item.user_properties.append(("failure_trace", preview))

        page = getattr(item, "_async_page", None)
        if page is not None:
            shot = _capture_screenshot(page)
            if shot:
                item.user_properties.append(("attachment1", shot))


def _capture_screenshot(page: Any) -> str:
    """Capture a base64 data-URI screenshot from an async Playwright page.

    Returns an empty string on any failure — never raises into the hook.
    """
    try:
        coro = page.screenshot(full_page=True)
        loop = asyncio.get_event_loop()
        if loop.is_running():
            data = asyncio.run_coroutine_threadsafe(coro, loop).result(timeout=10.0)
        else:
            data = asyncio.run(coro)
        encoded = base64.b64encode(data).decode("ascii")
        return f"data:image/png;base64,{encoded}"
    except Exception:
        return ""


# ─── Session summary ─────────────────────────────────────────────────────────

_session_start: float = 0.0
_session_results: dict[str, int] = {"passed": 0, "failed": 0, "skipped": 0, "errors": 0}


def pytest_sessionstart(session: pytest.Session) -> None:
    global _session_start
    _session_start = time.perf_counter()


@pytest.hookimpl(trylast=True)
def pytest_runtest_logreport(report: pytest.TestReport) -> None:
    if report.when != "call":
        if report.when == "setup" and report.outcome == "failed":
            _session_results["errors"] += 1
        return
    _session_results[report.outcome] = _session_results.get(report.outcome, 0) + 1


def pytest_sessionfinish(session: pytest.Session, exitstatus: int) -> None:
    """Write a small JSON summary alongside the JUnit XML for downstream parsing."""
    elapsed = time.perf_counter() - _session_start
    summary = {
        "exit_status": int(exitstatus),
        "elapsed_sec": round(elapsed, 4),
        **_session_results,
    }
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    SESSION_SUMMARY_PATH.write_text(json.dumps(summary, indent=2), encoding="utf-8")


__all__ = [
    "REPORTS_DIR",
    "SESSION_SUMMARY_PATH",
    "pytest_configure",
    "async_page",
    "pytest_runtest_makereport",
    "pytest_sessionstart",
    "pytest_sessionfinish",
]
